platform :ios, "7.0"

target "AOReportListTableViewControllerDemo" do
  pod 'AOReportListViewController', :path => '../'
  pod 'AOReportModels', :path => '~/Documents/AORepos/AOReportModels'
  pod 'AOReportNetworking', :path => '~/Documents/AORepos/AOReportNetworking'
  pod 'AOReportAdapter', :path => '~/Documents/AORepos/AOReportAdapter'
  pod 'AOReportControllers', :path => '~/Documents/AORepos/AOReportControllers'
  pod 'AOReportNavigationController', :path => '~/Documents/AORepos/AOReportNavigationController'
  
  pod 'AFNetworkActivityLogger', '~> 2.0'
  pod 'AFAmazonS3Client', :path => '~/Documents/Libraries/AFAmazonS3Client'
  pod 'UIScrollView-InfiniteScroll', '~> 0.2'
end
